version: "3"


services:
    nginx:
        container_name: nginx
        build: ./nginx
        image: nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./web:/web
          - ./log:/var/log/nginx
        depends_on:
          - web

    web:
        container_name: web
        build: ./web
        image : web
        restart: always
        command: uwsgi --ini uwsgi.ini

        volumes:
            - ./web:/web
           # - ./log:var/log/uwsgi
        expose:
            - "8000"

        depends_on:
            - db



    db :
        container_name: db
        image: postgres

        volumes :
            - ./db/data:/var/lib/postgresql/data
            
        ports:

            - "5432:5432"

        environment:

            - POSTGRES_USER=user

            - POSTGRES_PASSWORD=1234


