# Generated by Django 3.1.13 on 2021-08-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False, verbose_name='답변여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('content', models.TextField(null=True, verbose_name='내용')),
                ('parnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='board.question')),
            ],
            options={
                'verbose_name': '자유 게시판',
                'verbose_name_plural': '자유 게시판',
                'ordering': ('-created_at',),
            },
        ),
    ]
