# Generated by Django 3.1.13 on 2021-08-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Free_Board',
        ),
    ]
