# Generated by Django 3.1.13 on 2021-08-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210814_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('content', models.TextField(null=True, verbose_name='내용')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='free_board',
            name='state',
        ),
    ]
