# Generated by Django 3.1.13 on 2021-08-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_data', '0002_auto_20210814_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbhs1_menu',
            options={'verbose_name': '서서울관 하루식단', 'verbose_name_plural': '서서울관 하루식단'},
        ),
        migrations.AlterModelOptions(
            name='cbhs2_menu',
            options={'verbose_name': '동서울관 하루식단', 'verbose_name_plural': '동서울관 하루식단'},
        ),
        migrations.AlterModelOptions(
            name='cbhs3_menu',
            options={'verbose_name': '청주관 하루식단', 'verbose_name_plural': '청주관 하루식단'},
        ),
    ]
