# Generated by Django 3.1.6 on 2021-08-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbhs1_menu',
            name='B',
            field=models.CharField(max_length=255, verbose_name='아침'),
        ),
        migrations.AlterField(
            model_name='cbhs1_menu',
            name='B_num',
            field=models.IntegerField(default=0, verbose_name='아침 좋아요'),
        ),
        migrations.AlterField(
            model_name='cbhs1_menu',
            name='D',
            field=models.CharField(max_length=255, verbose_name='저녁'),
        ),
        migrations.AlterField(
            model_name='cbhs1_menu',
            name='D_num',
            field=models.IntegerField(default=0, verbose_name='저녁 좋아요'),
        ),
        migrations.AlterField(
            model_name='cbhs1_menu',
            name='L',
            field=models.CharField(max_length=255, verbose_name='점심'),
        ),
        migrations.AlterField(
            model_name='cbhs1_menu',
            name='L_num',
            field=models.IntegerField(default=0, verbose_name='점심 좋아요'),
        ),
        migrations.AlterField(
            model_name='cbhs2_menu',
            name='B',
            field=models.CharField(max_length=255, verbose_name='아침'),
        ),
        migrations.AlterField(
            model_name='cbhs2_menu',
            name='B_num',
            field=models.IntegerField(default=0, verbose_name='아침 좋아요'),
        ),
        migrations.AlterField(
            model_name='cbhs2_menu',
            name='D',
            field=models.CharField(max_length=255, verbose_name='저녁'),
        ),
        migrations.AlterField(
            model_name='cbhs2_menu',
            name='D_num',
            field=models.IntegerField(default=0, verbose_name='저녁 좋아요'),
        ),
        migrations.AlterField(
            model_name='cbhs2_menu',
            name='L',
            field=models.CharField(max_length=255, verbose_name='점심'),
        ),
        migrations.AlterField(
            model_name='cbhs2_menu',
            name='L_num',
            field=models.IntegerField(default=0, verbose_name='점심 좋아요'),
        ),
        migrations.AlterField(
            model_name='cbhs3_menu',
            name='B',
            field=models.CharField(max_length=255, verbose_name='아침'),
        ),
        migrations.AlterField(
            model_name='cbhs3_menu',
            name='B_num',
            field=models.IntegerField(default=0, verbose_name='아침 좋아요'),
        ),
        migrations.AlterField(
            model_name='cbhs3_menu',
            name='D',
            field=models.CharField(max_length=255, verbose_name='저녁'),
        ),
        migrations.AlterField(
            model_name='cbhs3_menu',
            name='D_num',
            field=models.IntegerField(default=0, verbose_name='저녁 좋아요'),
        ),
        migrations.AlterField(
            model_name='cbhs3_menu',
            name='L',
            field=models.CharField(max_length=255, verbose_name='점심'),
        ),
        migrations.AlterField(
            model_name='cbhs3_menu',
            name='L_num',
            field=models.IntegerField(default=0, verbose_name='점심 좋아요'),
        ),
    ]
